# Generated by Django 6.0.5 on 2026-05-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneddocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("processing", "Processing"),
                    ("pending", "Pending"),
                    ("ignored", "Ignored"),
                    ("renamed", "Renamed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
