# Generated by Django 6.0.5 on 2026-05-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scanner", "0002_alter_scanneddocument_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanneddocument",
            name="file_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
